---
title: "Comparison species and individual based networks"
author: "Elena Quintero"
date: "`r Sys.Date()`"
output: html_document
---

```{r include = F}
knitr::opts_chunk$set(message = FALSE)
knitr::opts_chunk$set(warning = FALSE)
```


```{r, message=F}
library(here)
library(tidyverse)
library(magrittr)
library(ggfortify)
library(bipartite)
library(igraph)
library(tnet)
library(patchwork)

theme_set(theme_minimal())
```

Load observed net-level metrics:

```{r}
net.level <- read.csv(here("data/net.level.selection.csv")) %>%
  mutate(type = recode(type, "ind"="ind-based", "sp"="sp-based"))

#glimpse(net.level)
```


Load null model derived net-level metrics:

```{r}
nulls <- read_rds(here("data/net_level_nulls.rds"))
```

Select only metrics of interest:

```{r}
metrics.of.interest <- c("connectance", 
                         "weighted.NODF", 
                         "M", 
                         "interaction.evenness",
                         "centralization.w",
                         "assortativity")
```


Summarize null model metrics:

```{r}
null.data.sum <- nulls |> 
  group_by(net_code) |> 
  summarise_at(c("connectance", 
                 "weighted.NODF", 
                 "assortativity", 
                 "interaction.evenness",
                 "M", 
                 "Alatalo.interaction.evenness", 
                 "centralization.w"), 
               c("mean", "sd"))
```


```{r}
df <- net.level |> 
  select(net_code, type, net_id, net_n, net_size, all_of(metrics.of.interest), Alatalo.interaction.evenness)|> 
  #mutate(source = "observed") |> 
  left_join(null.data.sum, by = "net_code") |> 
  rowwise() |> 
  mutate(zs_connectance = (connectance - connectance_mean) / connectance_sd,
         zs_weighted.NODF = (weighted.NODF - weighted.NODF_mean) / weighted.NODF_sd,
         zs_assortativity = (assortativity - assortativity_mean) / assortativity_sd,
         zs_M = (M - M_mean) / M_sd,
         zs_Alatalo.interaction.evenness = (Alatalo.interaction.evenness - Alatalo.interaction.evenness_mean) / Alatalo.interaction.evenness_sd,
         zs_interaction.evenness = (interaction.evenness - interaction.evenness_mean) / interaction.evenness_sd,
         zs_centralization.w = (centralization.w - centralization.w_mean) / centralization.w_sd ) #|> 
  #filter(net_code != "sp_09_01")
```

Convert null to long format:

```{r}
null.metrics.long <- nulls |> 
  select(net_code, net_n, net_size, type, all_of(metrics.of.interest)) |> 
  pivot_longer(cols = -c(1:4), names_to = "metric", values_to = "value")
#630,000 observations
```

Check null-models metrics distribution:

```{r fig.width=10, fig.height=8}
plot.fun <- function(x) {null.metrics.long |>
  filter(metric == {{x}}) |>
  ggplot(aes(x = value, fill = type)) +
  #geom_density(alpha = 0.5) +
  geom_histogram() +
  scale_fill_manual(values = c("black", "grey50")) +
  theme(legend.position = "none",
        axis.text.y = element_blank()) +
  labs(y = NULL, x = NULL, title =  {{x}}) + 
  facet_wrap(~net_code, scales = "free")}

plot.fun("connectance")
# plot.fun("weighted.NODF")
# plot.fun("interaction.evenness")
# plot.fun("M")
# plot.fun("assortativity")
# plot.fun("centralization.w")

```


```{r fig.width = 10, fig.height = 5}
obs.metrics.long <- df |> 
  select(net_code, net_n, net_size, type, all_of(metrics.of.interest)) |> 
  pivot_longer(cols = -c(1:4), names_to = "metric", values_to = "value")
#630 observations

zs.long <- df |> 
  select(net_code, net_n,  net_size, type, starts_with("zs")) |> 
  select(-c(zs_Alatalo.interaction.evenness)) |> 
  pivot_longer(cols = -c(1:4), names_to = "metric", values_to = "value") |> 
  mutate(metric = str_replace(metric, "zs_", ""))
#630 observations
```


```{r fig.width = 10, fig.height = 5}
p1 <- ggplot(obs.metrics.long, aes(x = value, fill = type)) + 
  geom_density(alpha = 0.5) + 
  facet_wrap(~metric, scales = "free", nrow = 1) + 
  #scale_fill_manual(values = c("black", "grey70")) +
  #scale_fill_manual(values = c("#F6CF71", "#66C5CC")) +
  scale_fill_manual(values = c("grey40", "#2F8AC4")) +
  theme(panel.background = element_rect(colour = "black"),
        axis.text.y = element_blank(),
        panel.grid.minor = element_blank(),
        panel.grid.major.y = element_blank()) + 
  labs(y = NULL, x = NULL, title = "Observed values",
       color = "Netwok n\type", fill = "Network \ntype")

p2 <- zs.long |> 
  ggplot(aes(x = value, fill = type)) + 
  geom_density(alpha = 0.5) + 
  facet_wrap(~metric, scales = "free", nrow = 1) + 
  #scale_fill_manual(values = c("black", "grey70")) +
  #scale_fill_manual(values = c("#F6CF71", "#66C5CC")) +
  scale_fill_manual(values = c("grey40", "#2F8AC4")) +
  theme(legend.position = "none",
        axis.text.y = element_blank(), 
        panel.background = element_rect(colour = "black"), 
        strip.background = element_rect(colour = "white"),
        panel.grid.minor = element_blank(),
        panel.grid.major.y = element_blank()) + 
  labs(y = NULL, x = NULL, title = "Null models z-scores")

p3 <- null.metrics.long |> 
  ggplot(aes(x = value, fill = type)) + 
  geom_density(alpha = 0.5) + 
  facet_wrap(~metric, scales = "free", nrow = 1) + 
  #scale_fill_manual(values = c("black", "grey70")) +
  #scale_fill_manual(values = c("#F6CF71", "#66C5CC")) +
  scale_fill_manual(values = c("grey40", "#2F8AC4")) +
  theme(legend.position = "none",
        axis.text.y = element_blank(), 
        panel.background = element_rect(colour = "black"), 
        strip.background = element_rect(colour = "white"),
        panel.grid.minor = element_blank(),
        panel.grid.major.y = element_blank()) + 
  labs(y = NULL, x = NULL, title = "Null models")

p1 / p3 + plot_layout(guides = "collect")

#ggsave(here("figs/figs_rev1/Fig_2_panels_A.pdf"), width = 10, height = 5)

p1 / p2 + plot_layout(guides = "collect")

#ggsave(here("figs/figs_rev1/Fig_2_panels_B.pdf"), width = 10, height = 5)

```

Nets with higher z-score in weigthed NODF

```{r}
zs.long |>
  filter(metric == "weighted.NODF") |>
  filter(value >= 10)
  arrange(desc(value))
```

Summary observed metrics:

```{r}
obs.metrics.long |> 
  group_by(type, metric) |> 
  summarise(mean(value))
```

