---
title: "node-level metrics"
author: "Elena Quintero"
date: "`r Sys.Date()`"
output: github_document
---

```{r include = F}
knitr::opts_chunk$set(message = FALSE)
knitr::opts_chunk$set(warning = FALSE)
```


```{r, message=F}
library(here)
library(tidyverse)
library(magrittr)
library(reshape2)
library(ggrepel)
library(patchwork)

theme_set(theme_bw())
```

Read networks:

```{r}
#Read list of names
nets_names <- list.files(path = here("networks/standardized/"), pattern = "_int")

#Create empty list
nets <- list()

#Add all read files to the list
for (i in 1:length(nets_names)){
  net_file <- paste0("networks/standardized/", nets_names[[i]])
  net <- read.csv(here(net_file))
  
  if(ncol(net)<2){
    net <- read.csv(here(net_file), sep = ";") #For those datasets saved with ; separation
  } else
  {}  

  net %<>% column_to_rownames("ind")
  nets[[i]] <- net #add to list
  names(nets)[i] <- nets_names[[i]] #name the list

  # assign(nets_names[[i]], net)
}
```

Read nets characteristics (name, site etc...)

```{r}
nets_char <- readxl::read_xlsx(here("data/selected_individual_networks.xlsx"))

nets_ID <- nets_char %>%
  select(net_id = code_ID,
         ref,
         plant_sp = `focus species`,
         pop = pop_site) %>%
  mutate(net_name = paste0(plant_sp, "_", pop)) %>%
  group_by(net_id) %>%
  mutate(net_n = cur_group_id())
```


Individual level metrics:

```{r}
library(bipartite)

bipartite.ind.level <- data.frame()

for (i in 1:length(nets)){

  ind.level <- specieslevel(nets[[i]], level = "lower")

  ind.level %<>% rownames_to_column("ind") %>%
  mutate(net_id = names(nets[i]),
         net_id = str_sub(net_id, 3, 7))
  
  bipartite.ind.level <- rbind(bipartite.ind.level, ind.level)
}

bipartite.ind.level %<>% group_by(net_id) %>% 
  mutate(net_n = cur_group_id()) %>% 
  mutate(ind_ID = paste0(net_id, "_", ind))
  
glimpse(bipartite.ind.level)
```


Mean niche overlap:

Using bray curtis dissmilarity index
```{r}
niche_overlap <- data.frame()

for (i in 1:length(nets)) {
  
  net <- as.data.frame(nets[[i]])
  net_id = names(nets[i]) %>% str_sub(3, 7)
  
  bray.overlap <- as.matrix(vegdist(net, method="bray")) %>% 
    as.data.frame() %>%
    rownames_to_column("ind") %>%
    summarise(ind = ind,
              mean.bray.overlap = rowMeans(select(., -1))) %>%
    mutate(net_id = net_id)
  
  jaccard.overlap <- as.matrix(vegdist(net, method="jaccard")) %>% 
    as.data.frame() %>%
    rownames_to_column("ind") %>%
    summarise(ind = ind,
              mean.jaccard.overlap = rowMeans(select(., -1))) %>%
    mutate(net_id = net_id)
  
  overlap <- left_join(bray.overlap, jaccard.overlap)
  
  niche_overlap <- rbind(niche_overlap, overlap)
}

niche_overlap %<>% mutate(ind_ID = paste0(net_id, "_", ind)) %>%
  mutate(mean.bray.overlap = 1 - mean.bray.overlap,
         mean.jaccard.overlap = 1 - mean.jaccard.overlap) #inverse, where 1 is full overlap, 0 no overlap

glimpse(niche_overlap)
```


Eigenvalue centrality - igraph:

```{r}
library(igraph)

metrics.igraph.ind <- data.frame()

for (i in seq_along(nets)){
  
  net <- as.data.frame(nets[[i]])

  inet <- graph_from_incidence_matrix(net, weighted= T,  add.names=NULL)
  
  eigen.centrality = eigen_centrality(inet)$vector
  net_id = str_sub(names(nets[i]), 3, 7)
  as_calc <- cbind(net_id, eigen.centrality) %>%
    as.data.frame() %>%
    rownames_to_column("ind") %>%
    mutate(ind_ID = paste0(net_id, "_", ind))
  
  metrics.igraph.ind <- rbind(metrics.igraph.ind, as_calc) 
}

metrics.igraph.ind %<>% 
  mutate(eigen.centrality = as.numeric(eigen.centrality))

glimpse(metrics.igraph.ind)
```

Closeness and betweenness - tnet:

```{r}
library(tnet)

mynets = nets[-c(18, 30, 31)] # remove nets "08_01", "12_06", "12_07"

metrics.tnet.ind <- data.frame()

for (i in seq_along(mynets)){
  
  net <- as.data.frame(mynets[[i]])
  
  inet <- graph_from_incidence_matrix(net, weighted= T,  add.names=NULL)
  NodeLabels <- V(inet)$name
  NodeType <- V(inet)$type
  nodes_id <- cbind(NodeLabels, NodeType) %>% as.data.frame() %>% 
    filter(NodeType == "FALSE") %>%
    select(ind = NodeLabels) %>%
    rownames_to_column("node")

  #w.tm <- tnet::as.tnet(net) #problem with Paco's net, so I do it manually
  tm <- get.edgelist(inet, names=FALSE)
  w <- E(inet)$weight
  w.tm <- cbind(tm, w)
  
  om.tm <- projecting_tm(tm, "Newman") #One mode projection
  om.w.tm <- projecting_tm(w.tm, "Newman") #One mode projection
  
  closeness <- tnet::closeness_w(om.tm) %>% as.data.frame() %>% 
    select(node, tm.closeness = closeness)
  w.closeness <- tnet::closeness_w(om.w.tm) %>% as.data.frame()  %>% 
    select(node, tm.w.closeness = closeness)
  betweenness <- tnet::betweenness_w(om.tm) %>% as.data.frame() %>% 
    select(node, tm.betweenness = betweenness)
  w.betweenness <- tnet::betweenness_w(om.w.tm) %>% as.data.frame() %>% 
    select(node, tm.w.betweenness = betweenness)
  w.mets <- full_join(closeness, w.closeness) %>%  # don't do cbind because in some nets closeness is not calculated for all nodes (bec of singletons)
    full_join(betweenness) %>% full_join(w.betweenness) %>% 
    mutate(node = as.character(node)) %>%
    left_join(nodes_id, by = "node") %>%
    mutate(tm.closeness = ifelse(is.na(tm.closeness), 0, tm.closeness),
           tm.w.closeness = ifelse(is.na(tm.w.closeness), 0, tm.w.closeness)) # assign zero values to nodes where no closeness.

  net_id = str_sub(names(mynets[i]), 3, 7)
  
  tnet_metrics <- cbind(net_id, w.mets[, -1])
  
  metrics.tnet.ind <- rbind(metrics.tnet.ind, tnet_metrics)
}

metrics.tnet.ind %<>% mutate(ind_ID = paste0(net_id, "_", ind))

glimpse(metrics.tnet.ind)
```

```{r}
ind.level.df <- bipartite.ind.level %<>% 
  left_join(niche_overlap, by = c("ind", "net_id", "ind_ID")) %>%
  left_join(metrics.igraph.ind, by = c("ind", "net_id", "ind_ID")) %>%
  left_join(metrics.tnet.ind, by = c("ind", "net_id", "ind_ID"))

glimpse(ind.level.df)
```

```{r}
write_csv(ind.level.df, here("data/ind.level.df.csv"))
```
