---
title: "Exploration of node level metrics - manual calculation and selection"
author: "Elena Quintero"
date: "`r Sys.Date()`"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(message = FALSE)
knitr::opts_chunk$set(warning = FALSE)
```

Libraries:

```{r}
library(here)
library(bipartite)
library(igraph)
library(tidyverse)
library(tidylog)
library(magrittr)
library(patchwork)
library(rcartocolor)
library(GGally)
```

-----------------


Load metrics from posteriors data:

```{r}
files <- list.files(here("data/net_metrics_posteriors/"))

#select only those files with node metrics (not net metrics)
files_nodes <- files[grep("node", files)]

df.metrics <- data.frame()

for (i in 1:length(files_nodes)) {
  
  df <- readRDS(here(paste0("data/net_metrics_posteriors/", files_nodes[i]))) |> 
    dplyr::select(-c(node,Fisher.alpha)) |> 
    mutate(net_ind = paste0(net_id, "-", ind))
  
  df.metrics <- rbind(df.metrics, df)
  
}

glimpse(df.metrics)

# no. of networks:
unique(df.metrics$net_id)
length(unique(df.metrics$net_id))

# no. of plant individuals:
length(unique(df.metrics$net_ind))
```

```{r}
info <- readxl::read_xlsx(here("data/selected_networks.xlsx")) |>
  filter(type == "ind") |> 
  select(net_id = code_ID, plant_sp)

net.cols <- read.csv(here("data/net_colors.csv"))

#Net colors:
cols.bio <- as.character(net.cols$cols_bioregions2)
names(cols.bio) <- as.character(net.cols$plant_sp)

cols.bio.d <- as.character(net.cols$cols_bioregions_d2)
names(cols.bio.d) <- as.character(net.cols$bioregion)

df.post <- df.metrics |> 
  left_join(info) |> 
  left_join(net.cols)
```

```{r}
df.mean <- df.post |> 
  group_by(net_id, plant_sp, bioregion, net_ind) |> 
  summarise_at(vars(degree:mean.jaccard.overlap), mean)
```


Plant individuals and species in each bioregion:

```{r}
df.mean |> 
  group_by(bioregion) |> 
  summarise(n_inds = n_distinct(net_ind),
            n_sp = n_distinct(plant_sp))
```


Full comparison metrics:

```{r, fig.width=12, fig.height=10}
metrics <- c("normalised.degree",
             "species.strength",
             "species.specificity.index",
             "weighted.closeness",
             "mean.bray.overlap")

ggpairs(
 df.mean, columns = metrics,
 lower = list(continuous = wrap("points", pch = 21, color = "white", fill= "black", size = 0.75))) + 
  theme(axis.text.x = element_text(angle = 90, hjust = 1))
```


```{r}
interest.metrics <- df.mean %>% 
  ungroup() %>% 
  dplyr::select(all_of(metrics))

source(here("functions/vif_function.R"))

vif_func(in_frame = as.data.frame(interest.metrics), thresh = 3, trace = T)
```


Metrics correlation:

```{r cor_selec_metrics, fig.width = 8, fig.height = 6}
net.level <- read.csv(here("data/net.level.selection.csv"))
n.animals <- net.level %>% 
  dplyr::select(net_id, 
         animals = number.of.species.HL, 
         net_size)

df <- df.mean %>%
  ungroup() %>% 
  dplyr::select(net_id, all_of(metrics)) %>%
  group_by(net_id) %>%
  mutate(plants = n()) %>%
  left_join(n.animals) %>%
  rename("Normalised degree" = normalised.degree,
         "Species strength" = species.strength,
         "Species specificity" = species.specificity.index,
         "Weighted closeness" = weighted.closeness,
         "Mean Bray overlap " = mean.bray.overlap,
         "Network size" = net_size)

library(ggcorrplot)
corr_matrix <- cor(df[-c(1,7,8)])
p.mat <- cor_pmat(df[-c(1,7,8)])

ggcorrplot(corr_matrix, type = "lower", show.diag = F,
           hc.order = F, lab = T)

ggsave(here("figs/Fig_S7_cor_node_metrics.png"), width = 6, height = 6)
```


## Node metrics distibution:

# Plot metrics distribution by net

```{r}
plot_density_metric <- function(metric){
    plot <- ggplot(df.mean, aes(x = {{metric}}, color = plant_sp)) + 
        geom_density(bw = 0.1) +
        scale_color_manual(values = cols.bio) + 
        theme(legend.position = "none") + 
        scale_x_continuous(limits = c(0,1)) +
        labs(y = NULL)
  
    plot
}

plot_density_metric(normalised.degree)

#facet wrap by net:
#plot_density_metric(normalised.degree) + facet_wrap(~fct_reorder(net_name, plant_plot_rank))
```


```{r}
p1 <- plot_density_metric(normalised.degree) + labs(x = "Normalised degree")
p2 <- plot_density_metric(species.strength) + labs(x = "Species strength")
p3 <- plot_density_metric(species.specificity.index) + labs(x = "Species specificity index")
p4 <- plot_density_metric(weighted.closeness) + labs(x = "Weighted closeness")
p5 <- plot_density_metric(mean.bray.overlap) + labs(x = "Mean Bray overlap")

(p1 + p3 + p4) / (p2 + p5) #+ plot_layout(labs(y = NULL))

design <- "
123
456
"  

(p1 + p2 + p3 + p5 + p4) + plot_layout(design = design)
```

