---
title: "Exploration net-level metrics "
author: "Elena Quintero"
date: "`r Sys.Date()`"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(message = FALSE)
knitr::opts_chunk$set(warning = FALSE)
```

Libraries:

```{r}
library(here)
library(tidyverse)
library(magrittr)
library(rcartocolor)
library(patchwork)
library(ggalt)
library(psych)
library(ggfortify)
library(ggrepel)
library(knitr)
library(kableExtra)
library(cluster)
library(GGally)
library(reshape2)
library(ggcorrplot)
theme_set(theme_minimal())
```


Load net-level metrics:
```{r}
net.level <- read.csv(here("data/net.level.selection.csv")) %>%
  mutate(WC.new  = exp(Shannon.diversity)/net_size) %>%
  mutate(type = recode(type, "ind"="ind-based", "sp"="sp-based"))

glimpse(net.level)
```


Cluster analysis for metrics:

```{r cluster_analysis, fig.width = 7, fig.height = 5}
df <- net.level %>% 
  dplyr::select(-c(net_id, links, net_n, type, net_code, unique.ints, code_ID,
                    ref, bioregion, country, plant_sp, n_nodes, study, WC.new)) %>%
  dplyr::select(-starts_with("niche.overlap.horn")) %>%
  dplyr::select(-starts_with("niche.overlap.jaccard")) %>%
  dplyr::select(-centr_binary) %>%
  scale() %>% t()

# Dissimilarity matrix
d <- dist(df, method = "euclidean")

# Hierarchical clustering using Complete Linkage
hc1 <- hclust(d, method = "complete")

# Plot the obtained dendrogram
plot(hc1, cex = 0.6, hang = -1)
#rect.hclust(hc1, k = 10)
# save as PDF here("analysis/_exploratory_analysis/_exploratory_figs/cluster_metrics.pdf"), width = 7, height = 5)
```

Compare the three niche overlap metrics:

```{r niche_overlap, fig.width = 7, fig.height = 5}
net.level %>%
  select(type, starts_with("niche")) %>% melt() %>%
  ggplot(aes(x = value, fill = type)) + 
  geom_density(alpha = 0.5) + 
  facet_wrap(~variable, ncol = 2) +
  scale_fill_carto_d()
```


Correlation between metrics:

```{r cor_all_metrics, fig.width = 12, fig.height = 10}
colnames(net.level)

all.net.metrics <- net.level %>%
  dplyr::select(-c(net_id, links, net_n, type, net_code,
                   code_ID, ref, bioregion, country,
                   plant_sp, n_nodes, study)) %>% 
  dplyr::select(-c(WC.new, starts_with("niche.overlap.horn"),
                   starts_with("niche.overlap.jaccard"))) %>% 
  select(order(desc(colnames(.)))) # arrange metrics by alphabetic order

corr_matrix <- cor(all.net.metrics)
p.mat <- cor_pmat(all.net.metrics, conf.level = 0.95)

ggcorrplot(corr_matrix, type = "full", show.diag = F,
           hc.order = F,
           p.mat = p.mat, pch = "*")

```


```{r}
glimpse(net.level)
metrics.of.interest.size <- c("connectance", 
                         "weighted.NODF", 
                         "M", 
                         "Alatalo.interaction.evenness",
                         "centralization.w",
                         "assortativity",
                         "net_size")

#Remove net_size
metrics.of.interest <- metrics.of.interest.size[metrics.of.interest.size != "net_size"]
```

Correlation between selected metrics:

```{r cor_selec_metrics, fig.width = 8, fig.height = 6}
corr_matrix <- cor(net.level[, metrics.of.interest.size])
p.mat <- cor_pmat(net.level[, metrics.of.interest.size], conf.level = 0.95)

ggcorrplot(corr_matrix, type = "lower",  lab = T) 

#ggsave(here("figs/cor_net_metrics_new.pdf"), width = 7, height=7)
```


VIF:

```{r}
source(here("functions/vif_function.R"))

vif_func(in_frame = net.level[, metrics.of.interest], thresh = 4, trace = T)
```


Full comparison metrics:

```{r pairs_selec_metrics, fig.width = 10, fig.height = 7}
ggpairs(net.level, columns = metrics.of.interest, 
        aes(color = type, fill = type),
        diag = list(continuous = wrap("densityDiag", alpha = 0.5)),
        lower = list(continuous = wrap("points", alpha = 0.5))) +
  scale_color_carto_d() +
  scale_fill_carto_d()
```


Selected metrics distribution:

```{r dist_selec_metrics, fig.width = 7, fig.height = 5}
p1 <- ggplot(melt(net.level[, c("type", metrics.of.interest)]), 
            aes(x=value, fill = type)) + 
  geom_histogram(alpha = 0.75, color = "grey30") +
  scale_fill_manual(values = c("black", "grey50")) +
  facet_grid(type~variable, scales = "free") + 
  labs(color = NULL, fill = NULL)

p2 <- ggplot(melt(net.level[, c("type", metrics.of.interest)]), 
            aes(x=value, fill = type)) + 
  geom_density(alpha = 0.75, color = "grey30") +
  scale_fill_manual(values = c("black", "grey50")) +
  facet_wrap(~variable, scales = "free", nrow = 1) + 
  labs(color = NULL, fill = NULL)

p1 / p2 + plot_layout(heights = c(2,1), guides = 'collect') & theme(legend.position = "bottom")

#ggsave(here("figs/net_metrics_distribution_new.pdf"), width = 10, height = 6)
```


Summary numbers:

```{r}
summary(net.level[, c("type", metrics.of.interest)])

net.level[, c("type", metrics.of.interest)] %>%
  #group_by(type) %>% 
  summarise_at(vars(connectance:assortativity), sd)


ind <- net.level[, c("type", metrics.of.interest)] %>% filter(type == "ind-based")
sp <- net.level[, c("type", metrics.of.interest)] %>% filter(type == "sp-based")
summary(ind)
summary(sp)

net.level[, c("type", metrics.of.interest)] %>%
  group_by(type) %>% 
  summarise_at(vars(connectance:assortativity), sd)


#coefficient of variation
net.level[, c("type", metrics.of.interest)] %>%
  #group_by(type) %>% 
  summarise(cv_con = sd(connectance) / mean(connectance) * 100,
            cv_nodf = sd(weighted.NODF) / mean(weighted.NODF) * 100,
            cv_mod = sd(M) / mean(M) * 100,
            cv_cen = sd(centralization.w) / mean(centralization.w) * 100,
            cv_ass = sd(assortativity) / mean(assortativity) * 100)
```


