---
title: "Web-level metrics"
author: "Elena Quintero"
date: "`r Sys.Date()`"
output: github_document
---


```{r include = F}
knitr::opts_chunk$set(message = FALSE)
knitr::opts_chunk$set(warning = FALSE)
```


```{r, message=F}
library(here)
library(tidyverse)
library(magrittr)
library(reshape2)
library(bipartite)
library(ggrepel)
library(patchwork)


theme_set(theme_bw())
```

Read all networks:

```{r Individual-based networks reading}
#Read list of names
nets_names <- list.files(path = here("networks/standardized/"), pattern = "_int")

#Create empty list
nets <- list()

#Add all read files to the list
for (i in 1:length(nets_names)){
  net_file <- paste0("networks/standardized/", nets_names[[i]])
  net <- read.csv(here(net_file))
  
  if(ncol(net)<2){
    net <- read.csv(here(net_file), sep = ";") #For those datasets saved with ; separation
  } else
  {}  

  net %<>% column_to_rownames("ind")
  nets[[i]] <- net #add to list
  names(nets)[i] <- nets_names[[i]] #name the list

  # assign(nets_names[[i]], net)
}
```

```{r Species-based networks reading}
#Read list of names
nets_names_sp <- list.files(path = here("networks/standardized/"), pattern = "stsp_")

#Create empty list
nets_sp <- list()

#Add all read files to the list
for (i in 1:length(nets_names_sp)){
  net_file_sp <- paste0("networks/standardized/", nets_names_sp[[i]])
  net_sp <- read.csv(here(net_file_sp))
  
  if(ncol(net_sp)<2){
    net_sp <- read.csv(here(net_file_sp), sep = ";") #For those datasets saved with ; separation
  } else
  {}  

  net_sp %<>% column_to_rownames("sp")
  nets_sp[[i]] <- net_sp #add to list
  names(nets_sp)[i] <- nets_names_sp[[i]] #name the list

  # assign(nets_names_sp[[i]], net_sp)
}
```

Read nets characteristics (name, site etc...)

```{r Reading net characteristics for Individial-based networks}
nets_char <- readxl::read_xlsx(here("data/selected_individual_networks.xlsx"))

nets_ID <- nets_char %>%
  select(net_id = code_ID,
         ref,
         plant_sp = `focus species`,
         pop = pop_site) %>%
  mutate(net_name = paste0(plant_sp, "_", pop)) %>%
  group_by(net_id) %>%
  mutate(net_n = cur_group_id())
```

```{r Reading net characteristics for Species-based networks}
nets_char_sp <- readxl::read_xlsx(here("data/selected_networks.xlsx"))

nets_ID_sp <- nets_char_sp %>% 
  filter (type == "sp") %>%
  select(net_id = code_ID,
         ref) %>%
  mutate(net_name = paste0(net_id, "_", ref)) %>%
  group_by(net_id) %>%
  mutate(net_n = cur_group_id())
```


Network level metrics:

```{r}
indices <- as.list(c("number of species", "connectance", "weighted connectance", 
                     "links per species", "NODF", "weighted NODF",
                     "cluster coefficient", "weighted cluster coefficient", 
                     "generality", "linkage density", 
                     "Shannon diversity", "interaction evenness", "Alatalo interaction evenness", "H2", 
                     "ISA", "SA", "web asymmetry",
                     "niche overlap", "extinction slope", "robustness"
                     ))

# METRICS NOT USED
# "Fisher alpha", "number of compartments", "compartment diversity", "mean number of links",
# "mean number of shared partners", "degree distribution", "togetherness", "C score", "V ratio"
# "discrepancy", "vulnerability", "fc"
```

```{r Network level metrics for Individual-based networks}
net.level.df <- data.frame()

for (i in 1:length(nets)){
  
  net.level <- networklevel(nets[[i]], indices)
  
  net.overlap2 <- networklevel(nets[[i]], "niche overlap", dist = "bray") %>% 
    t() %>% as.data.frame() %>%
    rename(niche.overlap.bray.HL = niche.overlap.HL ) %>%
    rename(niche.overlap.bray.LL = niche.overlap.LL)
  
  net.overlap3 <- networklevel(nets[[i]], "niche overlap", dist = "jaccard") %>%
    t() %>% as.data.frame() %>%
    rename(niche.overlap.jaccard.HL = niche.overlap.HL ) %>%
    rename(niche.overlap.jaccard.LL = niche.overlap.LL)
  
  links = sum(nets[[i]])
  
  net.level <- cbind(as.data.frame(t(net.level)), net.overlap2, net.overlap3) %>%
    mutate(net_size = number.of.species.HL * number.of.species.LL) %>%
    mutate(net_id = names(nets[i]),
         net_id = str_sub(net_id, 3, 7)) %>%
    mutate(links = links)
  
  net.level.df <- rbind(net.level.df, net.level)
}

net.level.df %<>% mutate(net_n = order(net_id))

glimpse(net.level.df)

write_csv(net.level.df, here("data/net.level.df.csv"))
```

```{r Network level metrics for Speciesl-based networks}
net.level.df.sp <- data.frame()

for (i in 1:length(nets_sp)){
  
  net.level.sp <- networklevel(nets_sp[[i]], indices)
  
  net.overlap2 <- networklevel(nets_sp[[i]], "niche overlap", dist = "bray") %>% 
    t() %>% as.data.frame() %>%
    rename(niche.overlap.bray.HL = niche.overlap.HL ) %>%
    rename(niche.overlap.bray.LL = niche.overlap.LL)
  
  net.overlap3 <- networklevel(nets_sp[[i]], "niche overlap", dist = "jaccard") %>%
    t() %>% as.data.frame() %>%
    rename(niche.overlap.jaccard.HL = niche.overlap.HL ) %>%
    rename(niche.overlap.jaccard.LL = niche.overlap.LL)
  
  links = sum(nets_sp[[i]])
  
  net.level.sp <- cbind(as.data.frame(t(net.level.sp)), net.overlap2, net.overlap3)  %>%
    mutate(net_size = number.of.species.HL * number.of.species.LL) %>%
    mutate(net_id = names(nets_sp[i]),
         net_id = str_sub(net_id, 1, 10)) %>%
    mutate(links = links)
  
  net.level.df.sp <- rbind(net.level.df.sp, net.level.sp)
}

net.level.df.sp %<>% mutate(net_n = order(net_id))

glimpse(net.level.df.sp)

write_csv(net.level.df.sp, here("data/net.level.df.sp.csv"))
```


Assortativity & centrality:
```{r}
library(igraph)

metrics.igraph.ind <- data.frame()

for (i in seq_along(nets)){
  
  net <- as.data.frame(nets[[i]])

  inet <- graph_from_incidence_matrix(net, weighted= T,  add.names=NULL)
  
  assortativity = assortativity_degree(inet)
  centr_binary = centr_eigen(inet, scale = TRUE, normalized = TRUE)$centralization
  centr.weighted.obs <- sum(max(eigen_centrality(inet)$vector) - eigen_centrality(inet)$vector)
  centralization.w <- centr.weighted.obs/ centr_eigen(inet)$theoretical_max
  net_id = str_sub(names(nets[i]), 3, 7)
  as_calc <- cbind(net_id, assortativity, centr_binary, centralization.w)
  
  metrics.igraph.ind <- rbind(metrics.igraph.ind, as_calc)
}
```


```{r}
metrics.igraph.sp <- data.frame()

for (i in seq_along(nets_sp)){
  
  net <- as.data.frame(nets_sp[[i]])

  inet <- graph_from_incidence_matrix(net, weighted=T,  add.names=NULL)
  
  assortativity = assortativity_degree(inet)
  centr_binary = centr_eigen(inet, scale = TRUE, normalized = TRUE)$centralization
  centr.weighted.obs <- sum(max(eigen_centrality(inet)$vector) - eigen_centrality(inet)$vector)
  centralization.w <- centr.weighted.obs/ centr_eigen(inet)$theoretical_max
  net_id = str_sub(names(nets_sp[i]), 6, 10)
  as_calc <- cbind(net_id, assortativity, centr_binary, centralization.w)
  
  metrics.igraph.sp <- rbind(metrics.igraph.sp, as_calc)
}
```


```{r}
metrics.igraph <- metrics.igraph.ind %>%
  mutate(type = "ind") %>%
  full_join(metrics.igraph.sp) %>%
  mutate(type = ifelse(is.na(type), "sp", type)) %>%
  mutate(assortativity = as.numeric(assortativity),
         centr_binary = as.numeric(centr_binary),
         centralization.w = as.numeric(centralization.w))

glimpse(metrics.igraph)

write.csv(metrics.igraph, here("data/igraph_metrics.csv"))
```

