---
title: "Webs standarisation"
author: "Elena Quintero"
date: "`r Sys.Date()`"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(here)
library(dplyr)
library(tidyverse)
```


Get list of net names in web folder:
```{r}
nets_names_ind <- list.files(path = here("networks/"), pattern = "_int") # For individual-based networks
nets_names_sp <- list.files(path = here("networks/"), pattern = "sp_")   # For species-based networks
```

Read webs and apply standardization:
```{r}
# Individual-based networks standardization
for (i in 1:length(nets_names_ind)){
  net_file <- paste0("networks/", nets_names_ind[[i]])
  net <- read.csv(here(net_file))
  if(ncol(net)<2){
    net <- read.csv(here(net_file), sep = ";")
  } else
  {}  
  
  net_mat <- net %>% column_to_rownames("ind") %>% as.matrix()
  
  mat_gts <- net_mat/sum(net_mat)
  
  net_gts <- as.data.frame(mat_gts) %>% rownames_to_column("ind")
  
  assign(paste0("st", nets_names_ind[[i]]), net_gts)
  
  write_csv(net_gts, here(paste0("networks/standardized/", "st", nets_names_ind[[i]])))
}

# Species-based networks standardization
for (i in 1:length(nets_names_sp)){
  net_file <- paste0("networks/", nets_names_sp[[i]])
  net <- read.csv(here(net_file))
  if(ncol(net)<2){
    net <- read.csv(here(net_file), sep = ";")
  } else
  {}  
  
  net_mat <- net %>% column_to_rownames("sp") %>% as.matrix()
  
  mat_gts <- net_mat/sum(net_mat)
  
  net_gts <- as.data.frame(mat_gts) %>% rownames_to_column("sp")
  
  assign(paste0("st", nets_names_sp[[i]]), net_gts)
  
  write_csv(net_gts, here(paste0("networks/standardized/", "st", nets_names_sp[[i]])))
}
```

Check all new nets sum up to 1:
```{r}
nets_names_st_ind <- list.files(path = here("networks/standardized/"), pattern = "_int") # For individual-based networks
nets_names_st_sp <- list.files(path = here("networks/standardized/"), pattern = "stsp_") # For species-based networks

# For individual-based networks
for (i in 1:length(nets_names_st_ind)){
  net_file <- paste0("networks/standardized/", nets_names_st_ind[[i]])
  net <- read.csv(here(net_file))
  
  print(nets_names_st_ind[i])
  print(sum(net[,-1]))
}

# For species-based networks
for (i in 1:length(nets_names_st_sp)){
  net_file <- paste0("networks/standardized/", nets_names_st_sp[[i]])
  net <- read.csv(here(net_file))
  
  print(nets_names_st_sp[i])
  print(sum(net[,-1]))
}
```

#